/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import excecao.ProdutoNaoEncontradoException;
import java.lang.reflect.Method;
import java.util.concurrent.Callable;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.T;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import modelo.Aniversariante;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import service.AniversarianteAppService;

/**
 *
 * @author Daian Martinho
 */
public class DialogAniversariante extends javax.swing.JDialog {

    private Aniversariante umAniversariante;   
    private JTable tabelaDeAniversariantes;
    public static AniversarianteAppService aniversarianteAppService;
    static {
        @SuppressWarnings("resource")
        ApplicationContext fabrica = new ClassPathXmlApplicationContext("beans-jpa.xml");
        aniversarianteAppService = (AniversarianteAppService) fabrica.getBean("aniversarianteAppService");
    }
    /**
     * Creates new form DialogAniversariante
     */
    public DialogAniversariante(java.awt.Frame parent, boolean modal, JTable tabelaDeAniversariantes) {
        super(parent, modal);
        initComponents();           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDeFestas = new javax.swing.JTable();
        editarBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();
        primeiroNomeCampo = new javax.swing.JTextField();
        enderecoCampo = new javax.swing.JTextField();
        mascRadio = new javax.swing.JRadioButton();
        telefoneLabel = new javax.swing.JLabel();
        dataAniversarioLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        femRadio = new javax.swing.JRadioButton();
        nomeDoPaiCampo = new javax.swing.JTextField();
        primeiroNomeLabel = new javax.swing.JLabel();
        nomeDaMaeCampo = new javax.swing.JTextField();
        dataAniversarioCampo = new javax.swing.JFormattedTextField();
        sobrenomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        telefoneCampo = new javax.swing.JFormattedTextField();
        nomeDaMaeLabel = new javax.swing.JLabel();
        sobrenomeCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailCampo = new javax.swing.JTextField();
        nomeDoPaiLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        novaFestaBtn = new javax.swing.JButton();
        salvarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaDeFestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaDeFestas);

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        removerBtn.setText("Remover");
        removerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(mascRadio);
        mascRadio.setText("Masculino");

        telefoneLabel.setText("Telefone:");

        dataAniversarioLabel.setText("Data do aniversário:");

        emailLabel.setText("Email:");

        buttonGroup1.add(femRadio);
        femRadio.setText("Feminino");

        primeiroNomeLabel.setText("Nome:");

        dataAniversarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAniversarioCampoActionPerformed(evt);
            }
        });

        sobrenomeLabel.setText("Sobrenome:");

        jLabel1.setText("Sexo:");

        nomeDaMaeLabel.setText("Nome da mãe:");

        jLabel2.setText("Endereço:");

        nomeDoPaiLabel.setText("Nome do pai:");

        jLabel3.setText("Histórico de Festas");

        novaFestaBtn.setText("Nova festa");
        novaFestaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaFestaBtnActionPerformed(evt);
            }
        });

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(primeiroNomeLabel)
                    .addComponent(nomeDaMaeLabel)
                    .addComponent(nomeDoPaiLabel)
                    .addComponent(telefoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(novaFestaBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(primeiroNomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sobrenomeLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mascRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(femRadio)
                                        .addGap(13, 13, 13)
                                        .addComponent(dataAniversarioLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataAniversarioCampo)
                                    .addComponent(sobrenomeCampo)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomeDoPaiCampo)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(telefoneCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(enderecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(emailLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(emailCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                        .addComponent(nomeDaMaeCampo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(salvarBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editarBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removerBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelarBtn)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarBtn)
                    .addComponent(removerBtn)
                    .addComponent(salvarBtn)
                    .addComponent(cancelarBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeiroNomeLabel)
                    .addComponent(primeiroNomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeLabel)
                    .addComponent(sobrenomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mascRadio)
                    .addComponent(femRadio)
                    .addComponent(jLabel1)
                    .addComponent(dataAniversarioLabel)
                    .addComponent(dataAniversarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDaMaeLabel)
                    .addComponent(nomeDaMaeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoPaiLabel)
                    .addComponent(nomeDoPaiCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(telefoneCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(enderecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(novaFestaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataAniversarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAniversarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAniversarioCampoActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        this.umAniversariante = new Aniversariante();
        umAniversariante.setPrimeiroNome(primeiroNomeCampo.getText());
        umAniversariante.setSobrenome(sobrenomeCampo.getText());
        umAniversariante.setSexo(mascRadio.isSelected() ? 1 : 0);
        aniversarianteAppService.inclui(umAniversariante);
        AniversarianteModel model = new AniversarianteModel();
        model.setBuscaPorNome("");
        this.tabelaDeAniversariantes.setModel(model);
        this.salvo();
        
        
        
    }//GEN-LAST:event_salvarBtnActionPerformed

    private void novaFestaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaFestaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaFestaBtnActionPerformed

    private void removerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtnActionPerformed
        try {
            int dialogResult = showConfirmDialog(null,"Deseja remover este aniversariante e suas festas?","Warning", JOptionPane.YES_NO_OPTION);            
            if(dialogResult == JOptionPane.YES_OPTION){
                aniversarianteAppService.exclui(this.umAniversariante);
                
                AniversarianteModel model = new AniversarianteModel();
                model.setBuscaPorNome("");                
                tabelaDeAniversariantes.setModel(model);
                this.dispose();
            }
            
        } catch (ProdutoNaoEncontradoException ex) {
            Logger.getLogger(DialogAniversariante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removerBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        editavel();
    }//GEN-LAST:event_editarBtnActionPerformed

    public void novo() {
        salvarBtn.setEnabled(true);
        editarBtn.setEnabled(false);
        removerBtn.setEnabled(false);
        cancelarBtn.setEnabled(true);
        habilitarEdicao(true);
    }
    public void editavel() {
        salvarBtn.setEnabled(true);
        editarBtn.setEnabled(false);
        removerBtn.setEnabled(true);
        cancelarBtn.setEnabled(true);
        habilitarEdicao(true);
    }
    public void exibicao() {
        salvarBtn.setEnabled(false);
        editarBtn.setEnabled(true);
        removerBtn.setEnabled(true);
        cancelarBtn.setEnabled(true);
        habilitarEdicao(false);
    }
    
    public void salvo() {
        salvarBtn.setEnabled(false);
        editarBtn.setEnabled(true);
        removerBtn.setEnabled(true);
        cancelarBtn.setEnabled(true);
        habilitarEdicao(false);
        
    }
    private void habilitarEdicao(boolean valor){
        primeiroNomeCampo.setEditable(valor);
        sobrenomeCampo.setEditable(valor);
        mascRadio.setEnabled(valor);
        femRadio.setEnabled(valor);
        dataAniversarioCampo.setEditable(valor);
        nomeDaMaeCampo.setEditable(valor);
        nomeDoPaiCampo.setEditable(valor);
        telefoneCampo.setEditable(valor);
        enderecoCampo.setEditable(valor);
        emailCampo.setEditable(valor);
    }
    
    public void carregaAniversariante(long aniversarianteID) throws ProdutoNaoEncontradoException{
        
        this.umAniversariante = aniversarianteAppService.recuperaUmAniversariante(aniversarianteID);
        FestaModel festaModel = new FestaModel();
        festaModel.setBuscaPorAniversarianteID(aniversarianteID);
        tabelaDeFestas.setModel(festaModel);             
        primeiroNomeCampo.setText(umAniversariante.getPrimeiroNome());
        sobrenomeCampo.setText(umAniversariante.getSobrenome());
        if(umAniversariante.getSexo() == 1){
            mascRadio.setEnabled(true);
        }else{
            femRadio.setEnabled(true);
        }
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JFormattedTextField dataAniversarioCampo;
    private javax.swing.JLabel dataAniversarioLabel;
    private javax.swing.JButton editarBtn;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField enderecoCampo;
    private javax.swing.JRadioButton femRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton mascRadio;
    private javax.swing.JTextField nomeDaMaeCampo;
    private javax.swing.JLabel nomeDaMaeLabel;
    private javax.swing.JTextField nomeDoPaiCampo;
    private javax.swing.JLabel nomeDoPaiLabel;
    private javax.swing.JButton novaFestaBtn;
    private javax.swing.JTextField primeiroNomeCampo;
    private javax.swing.JLabel primeiroNomeLabel;
    private javax.swing.JButton removerBtn;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JTextField sobrenomeCampo;
    private javax.swing.JLabel sobrenomeLabel;
    private javax.swing.JTable tabelaDeFestas;
    private javax.swing.JFormattedTextField telefoneCampo;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables
}
