/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import excecao.ProdutoNaoEncontradoException;
import java.awt.CardLayout;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Aniversariante;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import service.AniversarianteAppService;

/**
 *
 * @author Daian Martinho
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public static AniversarianteAppService aniversarianteAppService;
    static {
        @SuppressWarnings("resource")
        ApplicationContext fabrica = new ClassPathXmlApplicationContext("beans-jpa.xml");
        aniversarianteAppService = (AniversarianteAppService) fabrica.getBean("aniversarianteAppService");
    }
    public FramePrincipal() {
        initComponents();
        
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioBtn = new javax.swing.JButton();
        aniversariantesBtn = new javax.swing.JButton();
        festasBtn = new javax.swing.JButton();
        bodyContainer = new javax.swing.JPanel();
        inicioPainel = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        aniversariantesPainel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaDeAniversariantes = new javax.swing.JTable();
        novoBtn = new javax.swing.JButton();
        buscarAniversarianteBtn = new javax.swing.JButton();
        campoBuscaPrimeiroNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 0, 18)); // NOI18N
        jLabel1.setText("Imperador");

        inicioBtn.setText("Início");
        inicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBtnActionPerformed(evt);
            }
        });

        aniversariantesBtn.setText("Aniversariantes");
        aniversariantesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniversariantesBtnActionPerformed(evt);
            }
        });

        festasBtn.setText("Festas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inicioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aniversariantesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(festasBtn)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(inicioBtn)
                    .addComponent(aniversariantesBtn)
                    .addComponent(festasBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyContainer.setLayout(new java.awt.CardLayout());

        inicioPainel.setBorder(null);
        inicioPainel.setDividerLocation(240);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aniversariantes do mês"));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        inicioPainel.setLeftComponent(jScrollPane1);

        jSplitPane2.setBorder(null);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Próximas festas"));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jSplitPane2.setTopComponent(jScrollPane2);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Notificações"));

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jSplitPane2.setRightComponent(jScrollPane3);

        inicioPainel.setRightComponent(jSplitPane2);

        bodyContainer.add(inicioPainel, "inicioCard");

        tabelaDeAniversariantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaDeAniversariantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaDeAniversariantesMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaDeAniversariantes);

        novoBtn.setText("Novo aniversariante");
        novoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBtnActionPerformed(evt);
            }
        });

        buscarAniversarianteBtn.setText("Buscar");
        buscarAniversarianteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAniversarianteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aniversariantesPainelLayout = new javax.swing.GroupLayout(aniversariantesPainel);
        aniversariantesPainel.setLayout(aniversariantesPainelLayout);
        aniversariantesPainelLayout.setHorizontalGroup(
            aniversariantesPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aniversariantesPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aniversariantesPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(aniversariantesPainelLayout.createSequentialGroup()
                        .addComponent(novoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(116, 116, 116)
                        .addComponent(buscarAniversarianteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBuscaPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        aniversariantesPainelLayout.setVerticalGroup(
            aniversariantesPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aniversariantesPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aniversariantesPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buscarAniversarianteBtn)
                    .addComponent(campoBuscaPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bodyContainer.add(aniversariantesPainel, "aniversariantesCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(501, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBtnActionPerformed
        
        CardLayout lm = (CardLayout) bodyContainer.getLayout();
        lm.show(bodyContainer, "inicioCard");
    }//GEN-LAST:event_inicioBtnActionPerformed

    private void aniversariantesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniversariantesBtnActionPerformed
        CardLayout lm = (CardLayout)bodyContainer.getLayout();
        AniversarianteModel model = new AniversarianteModel();
        model.setBuscaPorNome("");
        tabelaDeAniversariantes.setModel(model);
        lm.show(bodyContainer,"aniversariantesCard");
    }//GEN-LAST:event_aniversariantesBtnActionPerformed

    private void novoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBtnActionPerformed
        DialogAniversariante dialog = new DialogAniversariante(this,true,tabelaDeAniversariantes);
        dialog.novo();
        dialog.setVisible(true);
        
    }//GEN-LAST:event_novoBtnActionPerformed

    private void buscarAniversarianteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAniversarianteBtnActionPerformed
        AniversarianteModel model = new AniversarianteModel();
        model.setBuscaPorNome(campoBuscaPrimeiroNome.getText());
        tabelaDeAniversariantes.setModel(model);
    }//GEN-LAST:event_buscarAniversarianteBtnActionPerformed

    private void tabelaDeAniversariantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeAniversariantesMousePressed
        if(evt.getClickCount()==2){
            DialogAniversariante dialog = new DialogAniversariante(this,true,tabelaDeAniversariantes);
            try {
                dialog.carregaAniversariante((long)tabelaDeAniversariantes.getValueAt(tabelaDeAniversariantes.getSelectedRow(),0));
                dialog.exibicao();
                dialog.setVisible(true);
            } catch (ProdutoNaoEncontradoException ex) {
                JOptionPane.showMessageDialog(null, "Ops! Aniversariante não encontrado.");
            }
            
        }
        
        
    }//GEN-LAST:event_tabelaDeAniversariantesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniversariantesBtn;
    private javax.swing.JPanel aniversariantesPainel;
    private javax.swing.JPanel bodyContainer;
    private javax.swing.JButton buscarAniversarianteBtn;
    private javax.swing.JTextField campoBuscaPrimeiroNome;
    private javax.swing.JButton festasBtn;
    private javax.swing.JButton inicioBtn;
    private javax.swing.JSplitPane inicioPainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton novoBtn;
    private javax.swing.JTable tabelaDeAniversariantes;
    // End of variables declaration//GEN-END:variables
}
